//GET http://localhost:3000/movies/10

//GET http://localhost:3000/movies/45

GET http://localhost:3000/movies/4

GET http://localhost:3000/movies/23

GET http://localhost:3000/movies/10

GET http://localhost:3000/movies/54

GET http://localhost:3000/movies/67

GET http://localhost:3000/movies/86

GET http://localhost:3000/movies/12

GET http://localhost:3000/movies/54